# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBfQ0HRlMEppV9RKC2iui2cO2Mse0MRl
"""

!pip install openai

import os
from openai import OpenAI

client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

# CELL 3 — CONFIGURATION

import json
import re

# OpenAI model used throughout the prototype
MODEL = "gpt-4o-mini"

# Possible validation results
VALID_STATUSES = {
    "valid",
    "invalid",
    "non_requirement",
    "ambiguous"
}

# Temporal and logical operators supported by the prototype
SUPPORTED_OPERATORS = {
    "ATOM",
    "NOT",
    "AND",
    "OR",
    "IMPLIES",
    "ALWAYS",
    "EVENTUALLY",
    "NEXT",
    "UNTIL",
    "WEAK_UNTIL",
    "RELEASE",
    "WITHIN"
}

print("Configuration loaded successfully.")
print("Model:", MODEL)
print("Supported operators:")
print(", ".join(sorted(SUPPORTED_OPERATORS)))

# CELL 4 — REQUIREMENT VALIDATOR

def validate_requirement(requirement):
    """
    Uses the LLM to determine whether an input sentence is a valid,
    formalizable system requirement.

    Possible statuses:
    - valid
    - invalid
    - non_requirement
    - ambiguous
    """

    if not isinstance(requirement, str):
        return {
            "status": "invalid",
            "reason": "The input must be provided as text.",
            "suggestion": "Provide a complete textual system requirement."
        }

    requirement = requirement.strip()

    if not requirement:
        return {
            "status": "invalid",
            "reason": "The input is empty.",
            "suggestion": "Enter a complete system requirement."
        }

    prompt = f"""
You are an expert in requirements engineering, controlled natural language,
and temporal logic for high-assurance systems.

Analyse the following input:

"{requirement}"

Classify it using exactly one of these statuses:

1. valid
   The sentence expresses a clear system requirement that can reasonably
   be represented using propositional logic, Linear Temporal Logic (LTL),
   or Metric Temporal Logic (MTL).

2. invalid
   The input is meaningless, incomplete, corrupted, or not understandable
   as a sentence.

3. non_requirement
   The sentence is understandable but does not prescribe, prohibit,
   constrain, or describe required system behaviour.

4. ambiguous
   The sentence appears to be a requirement, but its essential actors,
   events, conditions, actions, ordering, or logical relationships are
   too unclear to formalize reliably.

Important formalization rules:

- Words such as "always", "never", "eventually", "whenever", "until",
  "before", "after", "next", "unless", and "within" are valid temporal
  expressions.

- "Eventually" is a valid unbounded temporal concept in LTL.
  It does NOT require a numerical deadline or exact timeframe.

- Do not classify a requirement as ambiguous merely because it uses
  "eventually".

- A numerical time bound is required only when the sentence explicitly
  uses bounded language such as:
  "within 5 seconds", "no later than 10 minutes", or "for at least 2 hours".

- Domain-specific component names and technical events should be accepted
  when their relationship is clear.

- A requirement may be valid even if the physical implementation details
  are not specified.

- Modal words such as "must", "shall", "should", and "required to" can
  indicate system requirements.

Examples:

Input:
"The pressure valve must never exceed the maximum threshold."

Output status:
valid

Input:
"Whenever the main power supply fails, the backup generator must eventually activate."

Output status:
valid

Reason:
The trigger, required response, and unbounded eventuality are clear and
can be represented as G(main_power_supply_fails -> F(backup_generator_activates)).

Input:
"The alarm must activate within 5 seconds after a sensor fault."

Output status:
valid

Input:
"The system should work properly."

Output status:
ambiguous

Input:
"The weather is pleasant today."

Output status:
non_requirement

Input:
"Hi"

Output status:
invalid

Return only valid JSON using exactly this structure:

{{
    "status": "valid | invalid | non_requirement | ambiguous",
    "reason": "brief explanation",
    "suggestion": "empty string when valid, otherwise a useful correction"
}}
"""

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You classify system requirements for formal "
                        "temporal-logic translation. Return JSON only."
                    )
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            response_format={"type": "json_object"},
            temperature=0
        )

        content = response.choices[0].message.content
        result = json.loads(content)

        status = str(
            result.get("status", "")
        ).strip().lower()

        reason = str(
            result.get("reason", "")
        ).strip()

        suggestion = str(
            result.get("suggestion", "")
        ).strip()

        if status not in VALID_STATUSES:
            return {
                "status": "invalid",
                "reason": (
                    "The validator returned an unsupported status."
                ),
                "suggestion": (
                    "Review the requirement and try again."
                )
            }

        if not reason:
            reason = "No validation explanation was provided."

        if status == "valid":
            suggestion = ""

        return {
            "status": status,
            "reason": reason,
            "suggestion": suggestion
        }

    except json.JSONDecodeError:
        return {
            "status": "invalid",
            "reason": (
                "The validator returned malformed JSON."
            ),
            "suggestion": (
                "Run the validation again."
            )
        }

    except Exception as error:
        return {
            "status": "invalid",
            "reason": (
                f"Validation could not be completed: {error}"
            ),
            "suggestion": (
                "Check the API connection and rerun the cell."
            )
        }


print("Requirement validator loaded successfully.")

# CELL 4A — TEST REQUIREMENT VALIDATION

test_inputs = [
    "hi",
    "The weather is nice today.",
    "The system should work properly.",
    "Whenever the sensor fails, the alarm must activate."
]

for text in test_inputs:
    result = validate_requirement(text)

    print("=" * 70)
    print("INPUT:", text)
    print("STATUS:", result["status"])
    print("REASON:", result["reason"])

    if result["suggestion"]:
        print("SUGGESTION:", result["suggestion"])

# CELL 5 — SEMANTIC EXTRACTION INTO A LOGICAL AST

def extract_semantics(requirement):
    """
    Converts a valid natural-language requirement into a structured
    semantic representation.

    The LLM only interprets the language.
    Later cells will generate CNL and temporal logic deterministically.
    """

    extraction_prompt = """
You are an expert in requirements engineering and temporal logic.

Analyse this system requirement:

"<<REQUIREMENT>>"

Convert its meaning into a logical Abstract Syntax Tree (AST).

Supported operators:

- ATOM
- NOT
- AND
- OR
- IMPLIES
- ALWAYS
- EVENTUALLY
- NEXT
- UNTIL
- WEAK_UNTIL
- RELEASE
- WITHIN

Use these rules:

1. ATOM represents one complete and independently readable event,
state, condition, or action.

Each ATOM must preserve all semantically important information from
the original requirement, including:

- the acting subject or system component,
- the action or state,
- the affected object,
- relevant conditions,
- relevant thresholds,
- relevant qualifiers.

Do not remove the acting subject from an action atom.

Correct example:

{
  "operator": "ATOM",
  "text": "the control system triggers a safety alert",
  "proposition": "safety_alert_triggered"
}

Incorrect example:

{
  "operator": "ATOM",
  "text": "the safety alert is triggered",
  "proposition": "safety_alert_triggered"
}

The incorrect example loses the acting subject
"the control system".

2. Preserve the original semantic roles.

For a clause such as:

"The control system must trigger a safety alert"

the atom text must preserve:

- subject: the control system
- action: triggers
- object: a safety alert

Therefore use:

"the control system triggers a safety alert"

Do not convert an active clause into a passive clause when doing so
removes or hides the acting subject.

3. ATOM text must be written as a complete declarative proposition.

Examples:

{
  "operator": "ATOM",
  "text": "the sensor fails",
  "proposition": "sensor_fails"
}

{
  "operator": "ATOM",
  "text": "the battery storage system compensates",
  "proposition": "battery_compensates"
}

{
  "operator": "ATOM",
  "text": "the warning alarm activates",
  "proposition": "alarm_activates"
}

4. Do not include modal or temporal words inside ATOM text.

Remove words such as:

- must
- shall
- should
- always
- eventually
- never
- whenever
- until

These meanings must be represented using AST operators.

For example:

"The warning alarm must eventually activate"

must become:

EVENTUALLY(
    ATOM("the warning alarm activates")
)

The atom text must not be:

"the warning alarm must eventually activate"

5. Unary operators use:

{
  "operator": "ALWAYS",
  "operand": ...
}

Supported unary operators:

- NOT
- ALWAYS
- EVENTUALLY
- NEXT

6. Binary operators use:

{
  "operator": "IMPLIES",
  "left": ...,
  "right": ...
}

Supported binary operators:

- AND
- OR
- IMPLIES
- UNTIL
- WEAK_UNTIL
- RELEASE

7. WITHIN represents a bounded temporal requirement:

{
  "operator": "WITHIN",
  "operand": ...,
  "value": 5,
  "unit": "seconds"
}

8. Conditional requirements normally use:

ALWAYS(
    IMPLIES(
        trigger,
        required_response
    )
)

9. Whenever, every time, or if generally indicate implication.

10. Always, at all times, or continuously generally indicate ALWAYS.

11. Eventually indicates EVENTUALLY.

12. Never normally means:

ALWAYS(
    NOT(...)
)

13. "Must not happen until condition B" normally means:

NOT(action) UNTIL condition_B

14. For response requirements, preserve the complete response clause.

For example:

"Whenever a sensor fault is detected, the control system must
eventually trigger a safety alert."

Use:

ALWAYS(
    IMPLIES(
        ATOM(
            text = "a sensor fault is detected",
            proposition = "sensor_fault_detected"
        ),
        EVENTUALLY(
            ATOM(
                text = "the control system triggers a safety alert",
                proposition = "safety_alert_triggered"
            )
        )
    )
)

Do not use:

ATOM(
    text = "the safety alert is triggered",
    proposition = "safety_alert_triggered"
)

because that loses the acting subject "the control system".

15. For requirements such as:

"Whenever the sensor fails, the alarm must activate."

Use:

ALWAYS(
    IMPLIES(
        ATOM(
            text = "the sensor fails",
            proposition = "sensor_fails"
        ),
        EVENTUALLY(
            ATOM(
                text = "the alarm activates",
                proposition = "alarm_activates"
            )
        )
    )
)

16. When the response clause contains an explicit subject, preserve it
exactly in the response atom text.

Examples:

Input clause:
"the backup generator must activate"

Atom text:
"the backup generator activates"

Input clause:
"the battery storage system must compensate"

Atom text:
"the battery storage system compensates"

Input clause:
"the control system must trigger a safety alert"

Atom text:
"the control system triggers a safety alert"

17. Preserve descriptive words that distinguish one component from
another.

For example, preserve:

- warning alarm
- backup generator
- emergency shutdown procedure
- battery storage system
- main power supply

Do not shorten "the warning alarm" to "the alarm" unless the original
requirement itself uses only "the alarm".

18. Proposition names should be short snake_case identifiers.

The proposition name may summarize the event, but the ATOM text must
preserve the complete natural-language meaning.

Example:

{
  "text": "the control system triggers a safety alert",
  "proposition": "safety_alert_triggered"
}

19. Preserve numerical thresholds and timing constraints in atom text.

Example:

{
  "text": "the grid voltage drops below the minimum level",
  "proposition": "grid_voltage_drops_below_min"
}

20. Do not invent information that is not stated.

21. Do not delete explicitly stated subjects, components, objects,
conditions, thresholds, or timing information.

22. The entries in the "atoms" list must exactly correspond to the ATOM
nodes used in the AST.

Each atom must use the same "text" and "proposition" values in both
locations.

23. Before returning the JSON, verify that every important noun phrase
from the original requirement is represented in at least one ATOM,
unless it is only a modal or temporal expression.

In particular, for conditional response requirements, verify that:

- the trigger is preserved,
- the responding subject is preserved,
- the response action is preserved,
- the affected object is preserved.

Return only valid JSON in this exact top-level structure:

{
  "requirement_type": "brief descriptive category",
  "ast": {
    "operator": "one supported operator",
    "...": "fields required by that operator"
  },
  "atoms": [
    {
      "text": "complete natural-language proposition",
      "proposition": "snake_case_name"
    }
  ],
  "assumptions": [],
  "confidence": 0.0
}

The confidence value must be between 0 and 1.
""".replace("<<REQUIREMENT>>", requirement)

    try:
        response = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You extract structured semantics from formalizable "
                        "system requirements. Preserve every explicitly stated "
                        "acting subject, action, object, condition, threshold, "
                        "and component name in the AST atom text. Do not change "
                        "active clauses into passive clauses when this would "
                        "remove the acting subject. Return only valid JSON."
                    )
                },
                {
                    "role": "user",
                    "content": extraction_prompt
                }
            ]
        )

        result = json.loads(response.choices[0].message.content)

        required_fields = {
            "requirement_type",
            "ast",
            "atoms",
            "assumptions",
            "confidence"
        }

        missing_fields = required_fields - set(result.keys())

        if missing_fields:
            raise ValueError(
                f"Missing semantic fields: {sorted(missing_fields)}"
            )

        if not isinstance(result["ast"], dict):
            raise ValueError("The AST must be a JSON object.")

        root_operator = str(
            result["ast"].get("operator", "")
        ).strip().upper()

        if root_operator not in SUPPORTED_OPERATORS:
            raise ValueError(
                f"Unsupported root operator: {root_operator}"
            )

        result["ast"]["operator"] = root_operator

        confidence = float(result["confidence"])
        result["confidence"] = max(0.0, min(1.0, confidence))

        if not isinstance(result["atoms"], list):
            raise ValueError("Atoms must be returned as a list.")

        if not isinstance(result["assumptions"], list):
            raise ValueError("Assumptions must be returned as a list.")

        return {
            "success": True,
            "data": result,
            "error": ""
        }

    except Exception as error:
        return {
            "success": False,
            "data": None,
            "error": str(error)
        }


print("Semantic extractor loaded successfully.")

# CELL 5A — TEST SEMANTIC EXTRACTION

test_requirement = (
    "Whenever the main power supply fails, "
    "the backup generator must eventually activate."
)

semantic_result = extract_semantics(test_requirement)

print("=" * 80)
print("INPUT REQUIREMENT:")
print(test_requirement)
print("=" * 80)

if semantic_result["success"]:
    print("SEMANTIC EXTRACTION SUCCESSFUL")
    print(json.dumps(semantic_result["data"], indent=2))
else:
    print("SEMANTIC EXTRACTION FAILED")
    print("ERROR:", semantic_result["error"])

# CELL 5B — DETERMINISTIC SEMANTIC VERIFICATION AND REPAIR

import re
from copy import deepcopy


# ================================================================
# SUPPORTED AST OPERATORS
# ================================================================

SUPPORTED_OPERATORS = {
    "ATOM",
    "NOT",
    "ALWAYS",
    "EVENTUALLY",
    "IMPLIES",
    "UNTIL",
    "AND",
    "OR"
}


# ================================================================
# BASIC HELPERS
# ================================================================

def validate_proposition_name(proposition):
    """
    Checks whether an atomic proposition uses valid snake_case.
    """

    return (
        isinstance(proposition, str)
        and bool(
            re.fullmatch(
                r"[a-z][a-z0-9_]*",
                proposition.strip()
            )
        )
    )


# Compatibility with earlier diagnostic code.
def validate_atom_id(atom_id):
    return validate_proposition_name(atom_id)


def normalise_confidence(value, default=1.0):
    """
    Converts confidence to a value between 0.0 and 1.0.
    """

    try:
        value = float(value)

    except (TypeError, ValueError):
        value = float(default)

    return max(
        0.0,
        min(1.0, value)
    )


# ================================================================
# AST STRUCTURAL VALIDATION
# ================================================================

def validate_ast_structure(ast, path="ast"):
    """
    Recursively validates the AST structure.

    Returns:
        {
            "valid": bool,
            "errors": list
        }
    """

    errors = []

    if not isinstance(ast, dict):
        return {
            "valid": False,
            "errors": [
                f"{path} must be a dictionary."
            ]
        }

    operator = ast.get("operator")

    if operator not in SUPPORTED_OPERATORS:
        return {
            "valid": False,
            "errors": [
                (
                    f"{path} contains unsupported operator: "
                    f"{operator}"
                )
            ]
        }

    # ------------------------------------------------------------
    # ATOM
    # ------------------------------------------------------------

    if operator == "ATOM":
        text = ast.get("text")
        proposition = ast.get("proposition")

        if not isinstance(text, str) or not text.strip():
            errors.append(
                f"{path}.text must be non-empty text."
            )

        if not validate_proposition_name(proposition):
            errors.append(
                (
                    f"{path}.proposition must be a valid "
                    "snake_case identifier."
                )
            )

    # ------------------------------------------------------------
    # UNARY OPERATORS
    # ------------------------------------------------------------

    elif operator in {
        "NOT",
        "ALWAYS",
        "EVENTUALLY"
    }:
        if "operand" not in ast:
            errors.append(
                f"{path}.operand is required for {operator}."
            )

        else:
            child_result = validate_ast_structure(
                ast["operand"],
                f"{path}.operand"
            )

            errors.extend(
                child_result["errors"]
            )

    # ------------------------------------------------------------
    # BINARY OPERATORS
    # ------------------------------------------------------------

    elif operator in {
        "IMPLIES",
        "UNTIL",
        "AND",
        "OR"
    }:
        for side in ["left", "right"]:
            if side not in ast:
                errors.append(
                    f"{path}.{side} is required for {operator}."
                )

            else:
                child_result = validate_ast_structure(
                    ast[side],
                    f"{path}.{side}"
                )

                errors.extend(
                    child_result["errors"]
                )

    return {
        "valid": len(errors) == 0,
        "errors": errors
    }


# ================================================================
# ATOM COLLECTION
# ================================================================

def collect_ast_atoms(ast):
    """
    Collects all ATOM values from an AST.
    """

    if not isinstance(ast, dict):
        return []

    operator = ast.get("operator")

    if operator == "ATOM":
        return [
            {
                "text": ast.get("text"),
                "proposition": ast.get("proposition")
            }
        ]

    if operator in {
        "NOT",
        "ALWAYS",
        "EVENTUALLY"
    }:
        return collect_ast_atoms(
            ast.get("operand")
        )

    if operator in {
        "IMPLIES",
        "UNTIL",
        "AND",
        "OR"
    }:
        return (
            collect_ast_atoms(
                ast.get("left")
            )
            +
            collect_ast_atoms(
                ast.get("right")
            )
        )

    return []


def collect_atom_nodes(ast):
    """
    Collects complete ATOM nodes from an AST.
    """

    if not isinstance(ast, dict):
        return []

    operator = ast.get("operator")

    if operator == "ATOM":
        return [deepcopy(ast)]

    if operator in {
        "NOT",
        "ALWAYS",
        "EVENTUALLY"
    }:
        return collect_atom_nodes(
            ast.get("operand")
        )

    if operator in {
        "IMPLIES",
        "UNTIL",
        "AND",
        "OR"
    }:
        return (
            collect_atom_nodes(
                ast.get("left")
            )
            +
            collect_atom_nodes(
                ast.get("right")
            )
        )

    return []


def deduplicate_atoms(atoms):
    """
    Removes duplicate atoms while preserving their order.
    """

    unique_atoms = []
    seen = set()

    if not isinstance(atoms, list):
        return unique_atoms

    for atom in atoms:
        if not isinstance(atom, dict):
            continue

        proposition = atom.get("proposition")

        if (
            proposition
            and proposition not in seen
        ):
            unique_atoms.append({
                "text": atom.get("text"),
                "proposition": proposition
            })

            seen.add(proposition)

    return unique_atoms


# ================================================================
# TEXT MATCHING
# ================================================================

def normalise_text(text):
    """
    Normalises text for atom matching.
    """

    if not isinstance(text, str):
        return ""

    text = text.lower()

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


def get_matching_tokens(text):
    """
    Removes grammatical words and keeps semantic keywords.
    """

    stop_words = {
        "the",
        "a",
        "an",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "must",
        "shall",
        "should",
        "not",
        "until",
        "when",
        "whenever",
        "if",
        "after",
        "once",
        "then",
        "that",
        "it",
        "to",
        "of",
        "in",
        "on",
        "at"
    }

    return {
        token
        for token in normalise_text(text).split()
        if token not in stop_words
    }


def find_best_matching_atom(atom_nodes, phrase):
    """
    Finds the atom that best matches a phrase from the requirement.
    """

    phrase_tokens = get_matching_tokens(
        phrase
    )

    if not phrase_tokens:
        return None

    best_atom = None
    best_score = 0

    for atom in atom_nodes:
        atom_tokens = get_matching_tokens(
            atom.get("text", "")
        )

        overlap = len(
            phrase_tokens.intersection(
                atom_tokens
            )
        )

        if overlap > best_score:
            best_score = overlap
            best_atom = atom

    if best_score == 0:
        return None

    return deepcopy(best_atom)


# ================================================================
# RESPONSE PATTERN
# ================================================================

def is_triggered_response_requirement(requirement):
    """
    Detects triggered response requirements.

    Examples:
        The generator must activate when power fails.
        If voltage drops, the battery must compensate.
        Whenever a fault occurs, an alert must be issued.
    """

    text = normalise_text(
        requirement
    )

    has_trigger = bool(
        re.search(
            r"\b(when|whenever|if|after|once)\b",
            text
        )
    )

    has_obligation = bool(
        re.search(
            r"\b(must|shall|required|has to)\b",
            text
        )
    )

    # Prevent UNTIL requirements from being treated as responses.
    has_until = bool(
        re.search(
            r"\buntil\b",
            text
        )
    )

    return (
        has_trigger
        and has_obligation
        and not has_until
    )


def is_response_ast(ast):
    """
    Checks for ALWAYS(IMPLIES(trigger, response)).
    """

    return (
        isinstance(ast, dict)
        and ast.get("operator") == "ALWAYS"
        and isinstance(ast.get("operand"), dict)
        and ast["operand"].get("operator") == "IMPLIES"
    )


def response_has_eventually(ast):
    """
    Checks whether the response is already EVENTUALLY(response).
    """

    if not is_response_ast(ast):
        return False

    response = ast["operand"].get(
        "right"
    )

    return (
        isinstance(response, dict)
        and response.get("operator") == "EVENTUALLY"
    )


def repair_response_ast(ast):
    """
    Converts:

        ALWAYS(IMPLIES(trigger, response))

    into:

        ALWAYS(IMPLIES(trigger, EVENTUALLY(response)))
    """

    repaired_ast = deepcopy(ast)

    response = repaired_ast[
        "operand"
    ]["right"]

    repaired_ast[
        "operand"
    ]["right"] = {
        "operator": "EVENTUALLY",
        "operand": response
    }

    return repaired_ast


# ================================================================
# NEGATIVE UNTIL / PRECEDENCE PATTERN
# ================================================================

def parse_negative_until_requirement(requirement):
    """
    Parses:

        subject must not action until condition
    """

    if not isinstance(requirement, str):
        return None

    match = re.match(
        (
            r"^\s*"
            r"(?P<subject>.+?)"
            r"\s+(?:must|shall)\s+not\s+"
            r"(?P<action>.+?)"
            r"\s+until\s+"
            r"(?P<condition>.+?)"
            r"[.!?]?\s*$"
        ),
        requirement,
        flags=re.IGNORECASE
    )

    if not match:
        return None

    prohibited_event = (
        match.group("subject").strip()
        + " "
        + match.group("action").strip()
    )

    enabling_condition = (
        match.group("condition").strip()
    )

    return {
        "prohibited_event": prohibited_event,
        "enabling_condition": enabling_condition
    }


def build_negative_until_ast(
    requirement,
    original_ast
):
    """
    Builds the correct AST for:

        event B must not occur until condition A

    Correct structure:

        UNTIL(
            NOT(B),
            A
        )
    """

    parsed = parse_negative_until_requirement(
        requirement
    )

    if parsed is None:
        return None

    atom_nodes = collect_atom_nodes(
        original_ast
    )

    prohibited_atom = find_best_matching_atom(
        atom_nodes,
        parsed["prohibited_event"]
    )

    condition_atom = find_best_matching_atom(
        atom_nodes,
        parsed["enabling_condition"]
    )

    if (
        prohibited_atom is None
        or condition_atom is None
    ):
        return None

    if (
        prohibited_atom.get("proposition")
        ==
        condition_atom.get("proposition")
    ):
        return None

    return {
        "operator": "UNTIL",
        "left": {
            "operator": "NOT",
            "operand": prohibited_atom
        },
        "right": condition_atom
    }


# ================================================================
# RESULT CONSTRUCTION
# ================================================================

def build_verified_result(
    semantic_data,
    ast,
    status,
    reason,
    verifier_confidence
):
    """
    Builds a consistent verification result.
    """

    result_data = deepcopy(
        semantic_data
    )

    result_data["ast"] = ast

    result_data["atoms"] = deduplicate_atoms(
        collect_ast_atoms(ast)
    )

    result_data[
        "semantic_verification"
    ] = {
        "status": status,
        "reason": reason,
        "confidence": verifier_confidence
    }

    extraction_confidence = normalise_confidence(
        semantic_data.get(
            "confidence",
            1.0
        )
    )

    result_data["confidence"] = min(
        extraction_confidence,
        verifier_confidence
    )

    return {
        "success": True,
        "status": status,
        "data": result_data
    }


# ================================================================
# MAIN VERIFICATION FUNCTION
# ================================================================

def verify_and_repair_semantics(
    requirement,
    semantic_data
):
    """
    Validates and repairs the extracted AST using deterministic
    temporal requirement-pattern rules.

    Repair order:
        1. Negative UNTIL / precedence pattern
        2. Triggered response pattern
        3. Accept unchanged AST
    """

    if (
        not isinstance(requirement, str)
        or not requirement.strip()
    ):
        return {
            "success": False,
            "status": "needs_review",
            "error": (
                "The original requirement must be non-empty text."
            )
        }

    if not isinstance(semantic_data, dict):
        return {
            "success": False,
            "status": "needs_review",
            "error": (
                "Semantic data must be a dictionary."
            )
        }

    original_ast = semantic_data.get(
        "ast"
    )

    structure_result = validate_ast_structure(
        original_ast
    )

    if not structure_result["valid"]:
        return {
            "success": False,
            "status": "needs_review",
            "error": (
                "The extracted AST is structurally invalid."
            ),
            "details": structure_result["errors"]
        }

    # ------------------------------------------------------------
    # RULE 1 — NEGATIVE UNTIL / PRECEDENCE
    # ------------------------------------------------------------

    negative_until_ast = build_negative_until_ast(
        requirement,
        original_ast
    )

    if negative_until_ast is not None:
        repaired_structure = validate_ast_structure(
            negative_until_ast
        )

        if not repaired_structure["valid"]:
            return {
                "success": False,
                "status": "needs_review",
                "error": (
                    "The repaired UNTIL AST is structurally invalid."
                ),
                "details": repaired_structure["errors"]
            }

        if negative_until_ast != original_ast:
            return build_verified_result(
                semantic_data=semantic_data,
                ast=negative_until_ast,
                status="repaired",
                reason=(
                    "The UNTIL operands and negation were normalised. "
                    "The prohibited event is negated on the left of "
                    "UNTIL, and the enabling condition is on the right."
                ),
                verifier_confidence=0.95
            )

        return build_verified_result(
            semantic_data=semantic_data,
            ast=original_ast,
            status="accepted",
            reason=(
                "The negative UNTIL requirement already uses the "
                "correct precedence structure."
            ),
            verifier_confidence=1.0
        )

    # ------------------------------------------------------------
    # RULE 2 — TRIGGERED RESPONSE
    # ------------------------------------------------------------

    if (
        is_triggered_response_requirement(
            requirement
        )
        and is_response_ast(
            original_ast
        )
    ):
        if response_has_eventually(
            original_ast
        ):
            return build_verified_result(
                semantic_data=semantic_data,
                ast=original_ast,
                status="accepted",
                reason=(
                    "The triggered response already places "
                    "EVENTUALLY around the required response."
                ),
                verifier_confidence=1.0
            )

        repaired_response_ast = repair_response_ast(
            original_ast
        )

        repaired_structure = validate_ast_structure(
            repaired_response_ast
        )

        if not repaired_structure["valid"]:
            return {
                "success": False,
                "status": "needs_review",
                "error": (
                    "The repaired response AST is structurally invalid."
                ),
                "details": repaired_structure["errors"]
            }

        return build_verified_result(
            semantic_data=semantic_data,
            ast=repaired_response_ast,
            status="repaired",
            reason=(
                "The triggered response was normalised by placing "
                "EVENTUALLY around the required consequence."
            ),
            verifier_confidence=0.95
        )

    # ------------------------------------------------------------
    # RULE 3 — ACCEPT OTHER STRUCTURALLY VALID PATTERNS
    # ------------------------------------------------------------

    return build_verified_result(
        semantic_data=semantic_data,
        ast=original_ast,
        status="accepted",
        reason=(
            "The AST is structurally valid and no supported "
            "deterministic repair was required."
        ),
        verifier_confidence=1.0
    )


print("Cell 5B loaded successfully.")

# CELL 6 — DETERMINISTIC CNL GENERATOR

import re


def _split_subject_and_action(text):
    """
    Splits a simple energy-system clause into its subject and action.

    Example:
        "the backup generator activates"
        -> ("the backup generator", "activate")
    """

    text = str(text).strip()

    verb_forms = {
        "activates": "activate",
        "activate": "activate",
        "fails": "fail",
        "fail": "fail",
        "shuts down": "shut down",
        "shut down": "shut down",
        "triggers": "trigger",
        "trigger": "trigger",
        "compensates": "compensate",
        "compensate": "compensate",
        "exceeds": "exceed",
        "exceed": "exceed",
        "reaches": "reach",
        "reach": "reach",
        "monitors": "monitor",
        "monitor": "monitor",
        "is monitored": "be monitored",
        "are monitored": "be monitored",
        "is bypassed": "be bypassed",
        "are bypassed": "be bypassed",
        "occurs": "occur",
        "occur": "occur",
        "responds": "respond",
        "respond": "respond",
        "opens": "open",
        "open": "open",
        "closes": "close",
        "close": "close",
        "starts": "start",
        "start": "start",
        "stops": "stop",
        "stop": "stop"
    }

    ordered_forms = sorted(
        verb_forms,
        key=len,
        reverse=True
    )

    pattern = r"\b(" + "|".join(
        re.escape(form)
        for form in ordered_forms
    ) + r")\b"

    match = re.search(
        pattern,
        text,
        flags=re.IGNORECASE
    )

    if not match:
        return None, text

    subject = text[:match.start()].strip()
    matched_verb = match.group(0).lower()
    remainder = text[match.end():].strip()

    action = verb_forms[matched_verb]

    if remainder:
        action = f"{action} {remainder}"

    return subject, action


def _make_modal_clause(text, modal):
    """
    Converts an atomic clause into a modal requirement clause.

    Example:
        "the backup generator activates" + "must eventually"
        -> "the backup generator must eventually activate"
    """

    subject, action = _split_subject_and_action(text)

    if subject:
        return f"{subject} {modal} {action}"

    return f"{modal} {text}"


def ast_to_cnl(node):
    """
    Converts the verified semantic AST into Controlled Natural Language.
    This stage is deterministic and does not call the LLM.
    """

    if not isinstance(node, dict):
        raise ValueError("AST node must be a dictionary.")

    operator = str(
        node.get("operator", "")
    ).strip().upper()

    if operator == "ATOM":
        text = str(
            node.get("text", "")
        ).strip()

        if not text:
            raise ValueError(
                "ATOM node is missing its text."
            )

        return text

    if operator == "NOT":
        operand = ast_to_cnl(
            node["operand"]
        )

        return f"it is not the case that {operand}"

    if operator == "AND":
        left = ast_to_cnl(
            node["left"]
        )
        right = ast_to_cnl(
            node["right"]
        )

        return f"both {left} and {right}"

    if operator == "OR":
        left = ast_to_cnl(
            node["left"]
        )
        right = ast_to_cnl(
            node["right"]
        )

        return f"either {left} or {right}"

    if operator == "IMPLIES":
        left = ast_to_cnl(
            node["left"]
        )
        right = ast_to_cnl(
            node["right"]
        )

        return f"if {left}, then {right}"

    if operator == "ALWAYS":
        operand_node = node["operand"]

        # Response pattern:
        # G(trigger -> F(response))
        if (
            isinstance(operand_node, dict)
            and str(
                operand_node.get("operator", "")
            ).strip().upper() == "IMPLIES"
            and isinstance(
                operand_node.get("right"),
                dict
            )
            and str(
                operand_node["right"].get(
                    "operator",
                    ""
                )
            ).strip().upper() == "EVENTUALLY"
        ):
            trigger = ast_to_cnl(
                operand_node["left"]
            )

            response_node = operand_node[
                "right"
            ]["operand"]

            if (
                isinstance(response_node, dict)
                and str(
                    response_node.get(
                        "operator",
                        ""
                    )
                ).strip().upper() == "ATOM"
            ):
                response = _make_modal_clause(
                    response_node.get("text", ""),
                    "must eventually"
                )

                return f"whenever {trigger}, {response}"

        operand = ast_to_cnl(
            operand_node
        )

        return f"it is always the case that {operand}"

    if operator == "EVENTUALLY":
        operand = ast_to_cnl(
            node["operand"]
        )

        return f"eventually, {operand}"

    if operator == "NEXT":
        operand = ast_to_cnl(
            node["operand"]
        )

        return f"in the next state, {operand}"

    if operator == "UNTIL":
        left_node = node["left"]
        right_node = node["right"]

        # Negative precedence pattern:
        # NOT(prohibited_event) U enabling_condition
        if (
            isinstance(left_node, dict)
            and str(
                left_node.get("operator", "")
            ).strip().upper() == "NOT"
            and isinstance(
                left_node.get("operand"),
                dict
            )
            and str(
                left_node["operand"].get(
                    "operator",
                    ""
                )
            ).strip().upper() == "ATOM"
        ):
            prohibited_text = left_node[
                "operand"
            ].get("text", "")

            prohibited_clause = _make_modal_clause(
                prohibited_text,
                "must not"
            )

            condition = ast_to_cnl(
                right_node
            )

            return (
                f"{prohibited_clause} until {condition}"
            )

        left = ast_to_cnl(
            left_node
        )
        right = ast_to_cnl(
            right_node
        )

        return f"{left} must remain true until {right}"

    if operator == "WEAK_UNTIL":
        left = ast_to_cnl(
            node["left"]
        )
        right = ast_to_cnl(
            node["right"]
        )

        return f"{left} unless and until {right}"

    if operator == "RELEASE":
        left = ast_to_cnl(
            node["left"]
        )
        right = ast_to_cnl(
            node["right"]
        )

        return f"{right} must continue unless {left} occurs"

    if operator == "WITHIN":
        operand = ast_to_cnl(
            node["operand"]
        )
        value = node.get("value")
        unit = str(
            node.get("unit", "")
        ).strip()

        if value is None or not unit:
            raise ValueError(
                "WITHIN requires both a value and a unit."
            )

        return f"within {value} {unit}, {operand}"

    raise ValueError(
        f"Unsupported CNL operator: {operator}"
    )


def generate_cnl(semantic_data):
    """
    Generates the final Controlled Natural Language sentence.
    """

    if not isinstance(semantic_data, dict):
        raise ValueError(
            "Semantic data must be a dictionary."
        )

    ast = semantic_data.get("ast")

    if not isinstance(ast, dict):
        raise ValueError(
            "Semantic data does not contain a valid AST."
        )

    cnl = ast_to_cnl(ast).strip()

    if cnl:
        cnl = cnl[0].upper() + cnl[1:]

    if not cnl.endswith("."):
        cnl += "."

    return cnl


print("CNL generator loaded successfully.")

# CELL 6A — TEST CNL GENERATION

if semantic_result["success"]:
    generated_cnl = generate_cnl(semantic_result["data"])

    print("=" * 80)
    print("ORIGINAL REQUIREMENT:")
    print(test_requirement)
    print("=" * 80)
    print("GENERATED CNL:")
    print(generated_cnl)
else:
    print("Cannot generate CNL because semantic extraction failed.")

# CELL 7 — DETERMINISTIC TEMPORAL LOGIC GENERATOR

def ast_to_temporal_logic(node):
    """
    Converts the semantic AST into temporal logic.
    This stage is fully rule-based and does not use the LLM.
    """

    if not isinstance(node, dict):
        raise ValueError("AST node must be a dictionary.")

    operator = str(node.get("operator", "")).strip().upper()

    if operator == "ATOM":
        proposition = str(node.get("proposition", "")).strip()

        if not proposition:
            raise ValueError(
                "ATOM node is missing its proposition."
            )

        return proposition

    if operator == "NOT":
        operand = ast_to_temporal_logic(node["operand"])
        return f"!({operand})"

    if operator == "AND":
        left = ast_to_temporal_logic(node["left"])
        right = ast_to_temporal_logic(node["right"])
        return f"({left} & {right})"

    if operator == "OR":
        left = ast_to_temporal_logic(node["left"])
        right = ast_to_temporal_logic(node["right"])
        return f"({left} | {right})"

    if operator == "IMPLIES":
        left = ast_to_temporal_logic(node["left"])
        right = ast_to_temporal_logic(node["right"])
        return f"({left} -> {right})"

    if operator == "ALWAYS":
        operand = ast_to_temporal_logic(node["operand"])
        return f"G({operand})"

    if operator == "EVENTUALLY":
        operand = ast_to_temporal_logic(node["operand"])
        return f"F({operand})"

    if operator == "NEXT":
        operand = ast_to_temporal_logic(node["operand"])
        return f"X({operand})"

    if operator == "UNTIL":
        left = ast_to_temporal_logic(node["left"])
        right = ast_to_temporal_logic(node["right"])
        return f"({left} U {right})"

    if operator == "WEAK_UNTIL":
        left = ast_to_temporal_logic(node["left"])
        right = ast_to_temporal_logic(node["right"])
        return f"({left} W {right})"

    if operator == "RELEASE":
        left = ast_to_temporal_logic(node["left"])
        right = ast_to_temporal_logic(node["right"])
        return f"({left} R {right})"

    if operator == "WITHIN":
        operand = ast_to_temporal_logic(node["operand"])
        value = node.get("value")
        unit = str(node.get("unit", "")).strip().lower()

        if value is None or not unit:
            raise ValueError(
                "WITHIN requires both a value and a unit."
            )

        # Bounded eventually operator in Metric Temporal Logic
        return f"F[0,{value} {unit}]({operand})"

    raise ValueError(
        f"Unsupported temporal-logic operator: {operator}"
    )


def generate_temporal_logic(semantic_data):
    """
    Generates an LTL or MTL formula from semantic data.
    """

    if not isinstance(semantic_data, dict):
        raise ValueError("Semantic data must be a dictionary.")

    ast = semantic_data.get("ast")

    if not isinstance(ast, dict):
        raise ValueError(
            "Semantic data does not contain a valid AST."
        )

    formula = ast_to_temporal_logic(ast)

    logic_type = (
        "MTL"
        if contains_operator(ast, "WITHIN")
        else "LTL"
    )

    return {
        "logic_type": logic_type,
        "formula": formula
    }


def contains_operator(node, target_operator):
    """
    Recursively checks whether an operator occurs in the AST.
    """

    if not isinstance(node, dict):
        return False

    operator = str(node.get("operator", "")).strip().upper()

    if operator == target_operator.upper():
        return True

    for key in ("operand", "left", "right"):
        child = node.get(key)

        if isinstance(child, dict):
            if contains_operator(child, target_operator):
                return True

    return False


print("Temporal logic generator loaded successfully.")

# CELL 7A — TEST TEMPORAL LOGIC GENERATION

if semantic_result["success"]:
    temporal_result = generate_temporal_logic(
        semantic_result["data"]
    )

    print("=" * 80)
    print("ORIGINAL REQUIREMENT:")
    print(test_requirement)
    print("=" * 80)
    print("LOGIC TYPE:")
    print(temporal_result["logic_type"])
    print("=" * 80)
    print("TEMPORAL LOGIC FORMULA:")
    print(temporal_result["formula"])
else:
    print(
        "Cannot generate temporal logic because "
        "semantic extraction failed."
    )

# CELL 7B

import json
import re

def convert_temporal_logic_to_ast(ltl_formula):
    """
    Converts supported LTL formulas into the AST format used
    throughout the NeuroSymbolic Requirement Converter.
    """

    # ----------------------------
    # Basic validation
    # ----------------------------

    if not ltl_formula or not ltl_formula.strip():
        raise ValueError("Empty Temporal Logic formula.")

    ltl_formula = ltl_formula.strip()

    # Maintain same limitation as forward pipeline
    if re.search(r"\d", ltl_formula):
        raise ValueError(
            "Numeric constraints are outside the supported subset of this thesis."
        )

    prompt = f"""
You are an expert in Linear Temporal Logic.

Convert the following LTL formula into the EXACT AST schema below.

Supported operators:
- G
- F
- X
- U
- !
- &
- |
- ->

The AST schema MUST be:

{{
    "operator": "...",
    "operand": {{
        "operator": "ATOM",
        "text": "...",
        "proposition": "..."
    }}
}}

Rules:

- Preserve semantics exactly.
- proposition must match the atomic proposition in the LTL.
- text must be readable English.
- Do NOT add extra fields.
- Return ONLY valid JSON.

Examples:

Input:
F(system_activates_alarm)

Output:

{{
    "operator":"EVENTUALLY",
    "operand": {{
        "operator":"ATOM",
        "text":"the system activates the alarm",
        "proposition":"system_activates_alarm"
    }}
}}

Input:
G(system_logs_event)

Output:

{{
    "operator":"ALWAYS",
    "operand": {{
        "operator":"ATOM",
        "text":"the system logs the event",
        "proposition":"system_logs_event"
    }}
}}

Input:
!(alarm_active)

Output:

{{
    "operator":"NOT",
    "operand": {{
        "operator":"ATOM",
        "text":"alarm is active",
        "proposition":"alarm_active"
    }}
}}

Input:
request U grant

Output:

{{
    "operator":"UNTIL",
    "left": {{
        "operator":"ATOM",
        "text":"request",
        "proposition":"request"
    }},
    "right": {{
        "operator":"ATOM",
        "text":"grant",
        "proposition":"grant"
    }}
}}

Input:
request -> F(grant)

Output:

{{
    "operator":"IMPLIES",
    "left": {{
        "operator":"ATOM",
        "text":"request",
        "proposition":"request"
    }},
    "right": {{
        "operator":"EVENTUALLY",
        "operand": {{
            "operator":"ATOM",
            "text":"grant",
            "proposition":"grant"
        }}
    }}
}}

LTL:

{ltl_formula}
"""

    response = client.chat.completions.create(
        model=MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": "You convert Linear Temporal Logic into NeuroSymbolic AST."
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    ast = json.loads(response.choices[0].message.content)

    return ast

# Reverse Pipeline: Temporal Logic → Controlled Natural Language → English
def process_temporal_logic(ltl_formula):
    """
    Reverse conversion pipeline:
    Temporal Logic -> AST -> CNL -> English
    """

    try:
        # Step 1: Convert TL to AST
        ast = convert_temporal_logic_to_ast(ltl_formula)

        print("\n===== GENERATED AST =====")
        print(ast)

        # Wrap AST in the same structure used by the forward pipeline
        semantic_data = {
        "ast": ast
        }

        # Step 2: Generate CNL
        cnl = generate_cnl(semantic_data)

        # Step 3: Generate English
        english = generate_english(semantic_data)

        return {
            "status": "SUCCESS",
            "input_ltl": ltl_formula,
            "ast": ast,
            "controlled_natural_language": cnl,
            "english": english,

        }

    except Exception as e:

        return {
            "status": "FAILED",
            "input_ltl": ltl_formula,
            "error": str(e)
        }

# Test Reverse Pipeline
ltl = "F(system_activates_alarm)"

result = process_temporal_logic(ltl)

print("=" * 80)
print("REVERSE CONVERSION PIPELINE")
print("=" * 80)

print("STATUS:", result["status"])

if result["status"] == "SUCCESS":

    print("-" * 80)
    print("INPUT LTL:")
    print(result["input_ltl"])

    print("-" * 80)
    print("GENERATED AST:")
    print(result["ast"])

    print("-" * 80)
    print("CONTROLLED NATURAL LANGUAGE:")
    print(result["controlled_natural_language"])

    print("-" * 80)
    print("REGENERATED ENGLISH:")
    print(result["english"])



else:

    print(result["error"])

# CELL 8 — IMPROVED DETERMINISTIC ENGLISH GENERATOR


def ast_to_english(node):
    """
    Converts the verified semantic AST into readable English.
    This stage is deterministic and does not call the LLM.
    """

    if not isinstance(node, dict):
        raise ValueError("AST node must be a dictionary.")

    operator = str(
        node.get("operator", "")
    ).strip().upper()

    if operator == "ATOM":
        text = str(
            node.get("text", "")
        ).strip()

        if not text:
            raise ValueError(
                "ATOM node is missing its text."
            )

        return text

    if operator == "NOT":
        operand = ast_to_english(
            node["operand"]
        )

        return f"it is not the case that {operand}"

    if operator == "AND":
        left = ast_to_english(
            node["left"]
        )
        right = ast_to_english(
            node["right"]
        )

        return f"{left} and {right}"

    if operator == "OR":
        left = ast_to_english(
            node["left"]
        )
        right = ast_to_english(
            node["right"]
        )

        return f"{left} or {right}"

    if operator == "IMPLIES":
        left = ast_to_english(
            node["left"]
        )
        right = ast_to_english(
            node["right"]
        )

        return f"if {left}, then {right}"

    if operator == "ALWAYS":
        operand_node = node["operand"]

        # Natural English for the response pattern:
        # G(trigger -> F(response))
        if (
            isinstance(operand_node, dict)
            and str(
                operand_node.get("operator", "")
            ).strip().upper() == "IMPLIES"
            and isinstance(
                operand_node.get("right"),
                dict
            )
            and str(
                operand_node["right"].get(
                    "operator",
                    ""
                )
            ).strip().upper() == "EVENTUALLY"
        ):
            trigger = ast_to_english(
                operand_node["left"]
            )

            response_node = operand_node[
                "right"
            ]["operand"]

            if (
                isinstance(response_node, dict)
                and str(
                    response_node.get(
                        "operator",
                        ""
                    )
                ).strip().upper() == "ATOM"
            ):
                response = _make_modal_clause(
                    response_node.get("text", ""),
                    "must eventually"
                )

                return f"whenever {trigger}, {response}"

        operand = ast_to_english(
            operand_node
        )

        return f"it must always be true that {operand}"

    if operator == "EVENTUALLY":
        operand = ast_to_english(
            node["operand"]
        )

        return f"eventually, {operand}"

    if operator == "NEXT":
        operand = ast_to_english(
            node["operand"]
        )

        return f"in the next state, {operand}"

    if operator == "UNTIL":
        left_node = node["left"]
        right_node = node["right"]

        # Natural English for the negative precedence pattern:
        # NOT(prohibited_event) U enabling_condition
        if (
            isinstance(left_node, dict)
            and str(
                left_node.get("operator", "")
            ).strip().upper() == "NOT"
            and isinstance(
                left_node.get("operand"),
                dict
            )
            and str(
                left_node["operand"].get(
                    "operator",
                    ""
                )
            ).strip().upper() == "ATOM"
        ):
            prohibited_text = left_node[
                "operand"
            ].get("text", "")

            prohibited_clause = _make_modal_clause(
                prohibited_text,
                "must not"
            )

            condition = ast_to_english(
                right_node
            )

            return (
                f"{prohibited_clause} until {condition}"
            )

        left = ast_to_english(
            left_node
        )
        right = ast_to_english(
            right_node
        )

        return f"{left} must remain true until {right}"

    if operator == "WEAK_UNTIL":
        left = ast_to_english(
            node["left"]
        )
        right = ast_to_english(
            node["right"]
        )

        return (
            f"{left} must remain true until {right}; "
            f"however, {right} is not required to occur"
        )

    if operator == "RELEASE":
        left = ast_to_english(
            node["left"]
        )
        right = ast_to_english(
            node["right"]
        )

        return (
            f"{right} must remain true unless and until "
            f"{left} occurs"
        )

    if operator == "WITHIN":
        operand = ast_to_english(
            node["operand"]
        )
        value = node.get("value")
        unit = str(
            node.get("unit", "")
        ).strip()

        if value is None or not unit:
            raise ValueError(
                "WITHIN requires both a value and a unit."
            )

        return f"{operand} must occur within {value} {unit}"

    raise ValueError(
        f"Unsupported English-generation operator: {operator}"
    )


def generate_english(semantic_data):
    """
    Generates readable English from verified semantic data.
    """

    if not isinstance(semantic_data, dict):
        raise ValueError(
            "Semantic data must be a dictionary."
        )

    ast = semantic_data.get("ast")

    if not isinstance(ast, dict):
        raise ValueError(
            "Semantic data does not contain a valid AST."
        )

    sentence = ast_to_english(ast).strip()

    if sentence:
        sentence = sentence[0].upper() + sentence[1:]

    if not sentence.endswith("."):
        sentence += "."

    return sentence


print("Improved English generator loaded successfully.")

# CELL 8A — TEST ENGLISH GENERATION

if semantic_result["success"]:
    generated_english = generate_english(
        semantic_result["data"]
    )

    print("=" * 80)
    print("TEMPORAL LOGIC FORMULA:")
    print(temporal_result["formula"])
    print("=" * 80)
    print("GENERATED ENGLISH:")
    print(generated_english)
else:
    print(
        "Cannot generate English because "
        "semantic extraction failed."
    )

# CELL 9 — COMPLETE NL → CNL → TL → ENGLISH PIPELINE
# WITH INDEPENDENT SEMANTIC VERIFICATION


def process_requirement(requirement):
    """
    Runs the complete hybrid conversion pipeline:

    1. Validate the natural-language requirement.
    2. Extract semantic structure using the LLM.
    3. Verify and repair the AST deterministically.
    4. Generate CNL deterministically.
    5. Generate temporal logic deterministically.
    6. Regenerate readable English deterministically.
    """

    if not isinstance(requirement, str):
        return {
            "success": False,
            "stage": "input",
            "error": "The requirement must be provided as text."
        }

    requirement = requirement.strip()

    if not requirement:
        return {
            "success": False,
            "stage": "input",
            "error": "The requirement cannot be empty."
        }

    # ============================================================
    # STAGE 1 — INPUT VALIDATION
    # ============================================================

    validation = validate_requirement(requirement)

    if not isinstance(validation, dict):
        return {
            "success": False,
            "stage": "validation",
            "input": requirement,
            "error": (
                "The validator returned an invalid result format."
            )
        }

    if "success" in validation:
        if not validation.get("success", False):
            return {
                "success": False,
                "stage": "validation",
                "input": requirement,
                "error": validation.get(
                    "error",
                    "Requirement validation failed."
                )
            }

        validation_data = validation.get("data", {})

    else:
        validation_data = validation

    if not isinstance(validation_data, dict):
        return {
            "success": False,
            "stage": "validation",
            "input": requirement,
            "error": (
                "The validator did not return valid validation data."
            )
        }

    validation_status = str(
        validation_data.get("status", "")
    ).strip().lower()

    if validation_status != "valid":
        return {
            "success": False,
            "stage": "validation",
            "input": requirement,
            "validation": validation_data,
            "error": (
                "The input could not be processed as a "
                "valid formalizable requirement."
            )
        }

    # ============================================================
    # STAGE 2 — SEMANTIC EXTRACTION
    # ============================================================

    semantic_result = extract_semantics(requirement)

    if not isinstance(semantic_result, dict):
        return {
            "success": False,
            "stage": "semantic_extraction",
            "input": requirement,
            "validation": validation_data,
            "error": (
                "The semantic extractor returned an invalid result."
            )
        }

    if not semantic_result.get("success", False):
        return {
            "success": False,
            "stage": "semantic_extraction",
            "input": requirement,
            "validation": validation_data,
            "error": semantic_result.get(
                "error",
                "Semantic extraction failed."
            )
        }

    semantic_data = semantic_result.get("data")

    if not isinstance(semantic_data, dict):
        return {
            "success": False,
            "stage": "semantic_extraction",
            "input": requirement,
            "validation": validation_data,
            "error": (
                "The semantic extractor did not return "
                "valid semantic data."
            )
        }

    original_semantic_data = dict(semantic_data)
    original_ast = semantic_data.get("ast")

    # ============================================================
    # STAGE 3 — SEMANTIC VERIFICATION AND REPAIR
    # ============================================================

    verification_result = verify_and_repair_semantics(
        requirement,
        semantic_data
    )

    if not isinstance(verification_result, dict):
        return {
            "success": False,
            "stage": "semantic_verification",
            "input": requirement,
            "validation": validation_data,
            "semantics": semantic_data,
            "error": (
                "The semantic verifier returned an invalid result."
            )
        }

    if not verification_result.get("success", False):
        return {
            "success": False,
            "stage": "semantic_verification",
            "input": requirement,
            "validation": validation_data,
            "semantics": semantic_data,
            "semantic_verification": verification_result,
            "error": verification_result.get(
                "error",
                "Semantic verification failed."
            )
        }

    verified_semantic_data = verification_result.get("data")

    if not isinstance(verified_semantic_data, dict):
        return {
            "success": False,
            "stage": "semantic_verification",
            "input": requirement,
            "validation": validation_data,
            "semantics": semantic_data,
            "error": (
                "The semantic verifier did not return "
                "valid verified semantic data."
            )
        }

    semantic_data = verified_semantic_data

    semantic_verification = semantic_data.get(
        "semantic_verification",
        {}
    )

    # ============================================================
    # STAGES 4–6 — DETERMINISTIC GENERATION
    # ============================================================

    try:
        cnl = generate_cnl(
            semantic_data
        )

        temporal_logic = generate_temporal_logic(
            semantic_data
        )

        english = generate_english(
            semantic_data
        )

    except Exception as error:
        return {
            "success": False,
            "stage": "deterministic_generation",
            "input": requirement,
            "validation": validation_data,
            "original_semantics": original_semantic_data,
            "semantics": semantic_data,
            "semantic_verification": semantic_verification,
            "error": str(error)
        }

    if not isinstance(temporal_logic, dict):
        return {
            "success": False,
            "stage": "deterministic_generation",
            "input": requirement,
            "validation": validation_data,
            "semantics": semantic_data,
            "error": (
                "Temporal logic generation returned "
                "an invalid result."
            )
        }

    logic_type = temporal_logic.get("logic_type")
    formula = temporal_logic.get("formula")

    if not logic_type or not formula:
        return {
            "success": False,
            "stage": "deterministic_generation",
            "input": requirement,
            "validation": validation_data,
            "semantics": semantic_data,
            "error": (
                "Temporal logic generation did not return "
                "a complete logic result."
            )
        }

    return {
        "success": True,
        "input": requirement,
        "validation": validation_data,
        "original_semantics": original_semantic_data,
        "original_ast": original_ast,
        "semantics": semantic_data,
        "verified_ast": semantic_data.get("ast"),
        "semantic_verification": semantic_verification,
        "cnl": cnl,
        "logic_type": logic_type,
        "temporal_logic": formula,
        "english": english
    }


def display_pipeline_result(result):
    """
    Displays only the final user-facing conversion result.

    Detailed AST and verification information remains stored
    inside the result dictionary for evaluation and debugging,
    but it is not printed in the interactive interface.
    """

    print("=" * 80)
    print("NEUROSYMBOLIC REQUIREMENT CONVERSION PIPELINE")
    print("=" * 80)

    if not isinstance(result, dict):
        print("STATUS: FAILED")
        print("-" * 80)
        print("ERROR:")
        print("The pipeline returned an invalid result.")
        print("=" * 80)
        return

    if not result.get("success", False):
        print("STATUS: FAILED")
        print("-" * 80)
        print("FAILED STAGE:")
        print(
            result.get(
                "stage",
                "unknown"
            )
        )
        print("-" * 80)
        print("ERROR:")
        print(
            result.get(
                "error",
                "Unknown error"
            )
        )

        validation = result.get("validation")

        if isinstance(validation, dict):
            suggestion = str(
                validation.get(
                    "suggestion",
                    ""
                )
            ).strip()

            if suggestion:
                print("-" * 80)
                print("SUGGESTION:")
                print(suggestion)

        print("=" * 80)
        return

    print("STATUS: SUCCESS")
    print("-" * 80)

    print("INPUT — NATURAL LANGUAGE:")
    print(result["input"])

    print("-" * 80)

    print("CONTROLLED NATURAL LANGUAGE:")
    print(result["cnl"])

    print("-" * 80)

    print(f'{result["logic_type"]} FORMULA:')
    print(result["temporal_logic"])

    print("-" * 80)

    print("REGENERATED ENGLISH:")
    print(result["english"])

    print("-" * 80)

    print("FINAL CONFIDENCE:")
    print(
        result["semantics"].get(
            "confidence",
            "not provided"
        )
    )

    print("=" * 80)


print(
    "Complete conversion pipeline with semantic "
    "verification loaded successfully."
)

# CELL 9A — TEST COMPLETE PIPELINE

test_requirement = (
    "The backup generator must always activate "
    "when the main power supply fails."
)

result = process_requirement(test_requirement)

display_pipeline_result(result)

# CELL 10

def interactive_converter():

    line = "=" * 80
    section = "-" * 80

    print(line)
    print("              NEUROSYMBOLIC REQUIREMENT CONVERTER")
    print(line)

    print("\nSelect Conversion Mode")
    print("1. Natural Language → Temporal Logic")
    print("2. Temporal Logic → Natural Language")

    choice = input("\nEnter choice (1/2): ").strip()

    print(section)

    # =========================
    # NL -> TL
    # =========================

    if choice == "1":

        requirement = input("Enter Natural Language Requirement:\n\n")

        result = process_requirement(requirement)

        if not result["success"]:
            print("\n" + line)
            print("STATUS : FAILED")
            print(line)
            print(result)
            return

        print("\nConversion Mode : Natural Language → Temporal Logic")

        print("\n" + section)
        print("INPUT REQUIREMENT")
        print(section)
        print(result["input"])

        print("\n" + line)
        print("STATUS : SUCCESS")
        print(line)

        print("\n" + section)
        print("CONTROLLED NATURAL LANGUAGE (CNL)")
        print(section)
        print(result["cnl"])

        print("\n" + section)
        print("TEMPORAL LOGIC (LTL)")
        print(section)
        print(result["temporal_logic"])

        print("\n" + section)
        print("ABSTRACT SYNTAX TREE (AST)")
        print(section)
        print(result["verified_ast"])

        print("\n" + section)
        print("SEMANTIC CONFIDENCE INDICATOR")
        print(section)
        print(result["semantics"]["confidence"])



    # =========================
    # TL -> NL
    # =========================

    elif choice == "2":

        formula = input("Enter Temporal Logic Formula:\n\n")

        result = process_temporal_logic(formula)

        if result["status"] != "SUCCESS":
            print("\n" + line)
            print("STATUS : FAILED")
            print(line)
            print(result["error"])
            return

        print("\nConversion Mode : Temporal Logic → Natural Language")

        print("\n" + section)
        print("INPUT TEMPORAL LOGIC")
        print(section)
        print(result["input_ltl"])

        print("\n" + line)
        print("STATUS : SUCCESS")
        print(line)

        print("\n" + section)
        print("CONTROLLED NATURAL LANGUAGE (CNL)")
        print(section)
        print(result["controlled_natural_language"])

        print("\n" + section)
        print("REGENERATED ENGLISH")
        print(section)
        print(result["english"])

        print("\n" + section)
        print("ABSTRACT SYNTAX TREE (AST)")
        print(section)
        print(result["ast"])



    else:
        print("\nInvalid choice. Please enter 1 or 2.")

# CELL 10A — START INTERACTIVE CONVERTER

interactive_converter()

result = process_requirement("The system shall eventually activate the alarm.")
print(type(result))
print(result)